//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36323
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GhigoWeb.BancaSellaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://ecomm.sella.it/", ConfigurationName="BancaSellaWS.WSCryptDecryptSoap")]
    public interface WSCryptDecryptSoap {
        
        // CODEGEN: Parameter 'shopLogin' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="https://ecomm.sella.it/Encrypt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GhigoWeb.BancaSellaWS.EncryptResponse Encrypt(GhigoWeb.BancaSellaWS.EncryptRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ecomm.sella.it/Encrypt", ReplyAction="*")]
        System.Threading.Tasks.Task<GhigoWeb.BancaSellaWS.EncryptResponse> EncryptAsync(GhigoWeb.BancaSellaWS.EncryptRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ecomm.sella.it/Decrypt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode Decrypt(string shopLogin, string CryptedString);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ecomm.sella.it/Decrypt", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> DecryptAsync(string shopLogin, string CryptedString);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36323")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ecomm.sella.it/")]
    public partial class ShippingDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string shipToNameField;
        
        private string shipToStreetField;
        
        private string shipToCityField;
        
        private string shipToStateField;
        
        private string shipToCountryCodeField;
        
        private string shipToZipField;
        
        private string shipToStreet2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string shipToName {
            get {
                return this.shipToNameField;
            }
            set {
                this.shipToNameField = value;
                this.RaisePropertyChanged("shipToName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string shipToStreet {
            get {
                return this.shipToStreetField;
            }
            set {
                this.shipToStreetField = value;
                this.RaisePropertyChanged("shipToStreet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string shipToCity {
            get {
                return this.shipToCityField;
            }
            set {
                this.shipToCityField = value;
                this.RaisePropertyChanged("shipToCity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string shipToState {
            get {
                return this.shipToStateField;
            }
            set {
                this.shipToStateField = value;
                this.RaisePropertyChanged("shipToState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string shipToCountryCode {
            get {
                return this.shipToCountryCodeField;
            }
            set {
                this.shipToCountryCodeField = value;
                this.RaisePropertyChanged("shipToCountryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string shipToZip {
            get {
                return this.shipToZipField;
            }
            set {
                this.shipToZipField = value;
                this.RaisePropertyChanged("shipToZip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string shipToStreet2 {
            get {
                return this.shipToStreet2Field;
            }
            set {
                this.shipToStreet2Field = value;
                this.RaisePropertyChanged("shipToStreet2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36323")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ecomm.sella.it/")]
    public partial class RedItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string item_ProductCodeField;
        
        private string item_StockKeepingUnitField;
        
        private string item_DescriptionField;
        
        private string item_QuantityField;
        
        private string item_UnitCostField;
        
        private string item_TotalCostField;
        
        private string item_ShippingNumberField;
        
        private string item_GiftMessageField;
        
        private string item_PartEAN_NumberField;
        
        private string item_ShippingCommentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Item_ProductCode {
            get {
                return this.item_ProductCodeField;
            }
            set {
                this.item_ProductCodeField = value;
                this.RaisePropertyChanged("Item_ProductCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Item_StockKeepingUnit {
            get {
                return this.item_StockKeepingUnitField;
            }
            set {
                this.item_StockKeepingUnitField = value;
                this.RaisePropertyChanged("Item_StockKeepingUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Item_Description {
            get {
                return this.item_DescriptionField;
            }
            set {
                this.item_DescriptionField = value;
                this.RaisePropertyChanged("Item_Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Item_Quantity {
            get {
                return this.item_QuantityField;
            }
            set {
                this.item_QuantityField = value;
                this.RaisePropertyChanged("Item_Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Item_UnitCost {
            get {
                return this.item_UnitCostField;
            }
            set {
                this.item_UnitCostField = value;
                this.RaisePropertyChanged("Item_UnitCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Item_TotalCost {
            get {
                return this.item_TotalCostField;
            }
            set {
                this.item_TotalCostField = value;
                this.RaisePropertyChanged("Item_TotalCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Item_ShippingNumber {
            get {
                return this.item_ShippingNumberField;
            }
            set {
                this.item_ShippingNumberField = value;
                this.RaisePropertyChanged("Item_ShippingNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Item_GiftMessage {
            get {
                return this.item_GiftMessageField;
            }
            set {
                this.item_GiftMessageField = value;
                this.RaisePropertyChanged("Item_GiftMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Item_PartEAN_Number {
            get {
                return this.item_PartEAN_NumberField;
            }
            set {
                this.item_PartEAN_NumberField = value;
                this.RaisePropertyChanged("Item_PartEAN_Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Item_ShippingComments {
            get {
                return this.item_ShippingCommentsField;
            }
            set {
                this.item_ShippingCommentsField = value;
                this.RaisePropertyChanged("Item_ShippingComments");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36323")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ecomm.sella.it/")]
    public partial class RedItems : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numberOfItemsField;
        
        private RedItem[] red_ItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NumberOfItems {
            get {
                return this.numberOfItemsField;
            }
            set {
                this.numberOfItemsField = value;
                this.RaisePropertyChanged("NumberOfItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Red_Item", Order=1)]
        public RedItem[] Red_Item {
            get {
                return this.red_ItemField;
            }
            set {
                this.red_ItemField = value;
                this.RaisePropertyChanged("Red_Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36323")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ecomm.sella.it/")]
    public partial class RedCustomerData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string merchantWebSiteField;
        
        private string customer_IPAddressField;
        
        private string pC_FingerPrintField;
        
        private string previousCustomerField;
        
        private string red_Merchant_IDField;
        
        private string red_ServiceTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MerchantWebSite {
            get {
                return this.merchantWebSiteField;
            }
            set {
                this.merchantWebSiteField = value;
                this.RaisePropertyChanged("MerchantWebSite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Customer_IPAddress {
            get {
                return this.customer_IPAddressField;
            }
            set {
                this.customer_IPAddressField = value;
                this.RaisePropertyChanged("Customer_IPAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PC_FingerPrint {
            get {
                return this.pC_FingerPrintField;
            }
            set {
                this.pC_FingerPrintField = value;
                this.RaisePropertyChanged("PC_FingerPrint");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PreviousCustomer {
            get {
                return this.previousCustomerField;
            }
            set {
                this.previousCustomerField = value;
                this.RaisePropertyChanged("PreviousCustomer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Red_Merchant_ID {
            get {
                return this.red_Merchant_IDField;
            }
            set {
                this.red_Merchant_IDField = value;
                this.RaisePropertyChanged("Red_Merchant_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Red_ServiceType {
            get {
                return this.red_ServiceTypeField;
            }
            set {
                this.red_ServiceTypeField = value;
                this.RaisePropertyChanged("Red_ServiceType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36323")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ecomm.sella.it/")]
    public partial class RedBillingInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string billing_IdField;
        
        private string billing_NameField;
        
        private string billing_SurnameField;
        
        private string billing_DateOfBirthField;
        
        private string billing_EmailField;
        
        private string billing_AddressField;
        
        private string billing_Address2Field;
        
        private string billing_CityField;
        
        private string billing_StateCodeField;
        
        private string billing_CountryField;
        
        private string billing_PostalCodeField;
        
        private string billing_HomePhoneField;
        
        private string billing_WorkPhoneField;
        
        private string billing_MobilePhoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Billing_Id {
            get {
                return this.billing_IdField;
            }
            set {
                this.billing_IdField = value;
                this.RaisePropertyChanged("Billing_Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Billing_Name {
            get {
                return this.billing_NameField;
            }
            set {
                this.billing_NameField = value;
                this.RaisePropertyChanged("Billing_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Billing_Surname {
            get {
                return this.billing_SurnameField;
            }
            set {
                this.billing_SurnameField = value;
                this.RaisePropertyChanged("Billing_Surname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Billing_DateOfBirth {
            get {
                return this.billing_DateOfBirthField;
            }
            set {
                this.billing_DateOfBirthField = value;
                this.RaisePropertyChanged("Billing_DateOfBirth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Billing_Email {
            get {
                return this.billing_EmailField;
            }
            set {
                this.billing_EmailField = value;
                this.RaisePropertyChanged("Billing_Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Billing_Address {
            get {
                return this.billing_AddressField;
            }
            set {
                this.billing_AddressField = value;
                this.RaisePropertyChanged("Billing_Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Billing_Address2 {
            get {
                return this.billing_Address2Field;
            }
            set {
                this.billing_Address2Field = value;
                this.RaisePropertyChanged("Billing_Address2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Billing_City {
            get {
                return this.billing_CityField;
            }
            set {
                this.billing_CityField = value;
                this.RaisePropertyChanged("Billing_City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Billing_StateCode {
            get {
                return this.billing_StateCodeField;
            }
            set {
                this.billing_StateCodeField = value;
                this.RaisePropertyChanged("Billing_StateCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Billing_Country {
            get {
                return this.billing_CountryField;
            }
            set {
                this.billing_CountryField = value;
                this.RaisePropertyChanged("Billing_Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Billing_PostalCode {
            get {
                return this.billing_PostalCodeField;
            }
            set {
                this.billing_PostalCodeField = value;
                this.RaisePropertyChanged("Billing_PostalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Billing_HomePhone {
            get {
                return this.billing_HomePhoneField;
            }
            set {
                this.billing_HomePhoneField = value;
                this.RaisePropertyChanged("Billing_HomePhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Billing_WorkPhone {
            get {
                return this.billing_WorkPhoneField;
            }
            set {
                this.billing_WorkPhoneField = value;
                this.RaisePropertyChanged("Billing_WorkPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Billing_MobilePhone {
            get {
                return this.billing_MobilePhoneField;
            }
            set {
                this.billing_MobilePhoneField = value;
                this.RaisePropertyChanged("Billing_MobilePhone");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36323")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ecomm.sella.it/")]
    public partial class RedShippingInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string shipping_NameField;
        
        private string shipping_SurnameField;
        
        private string shipping_EmailField;
        
        private string shipping_AddressField;
        
        private string shipping_Address2Field;
        
        private string shipping_CityField;
        
        private string shipping_StateCodeField;
        
        private string shipping_CountryField;
        
        private string shipping_PostalCodeField;
        
        private string shipping_HomePhoneField;
        
        private string shipping_MobilePhoneField;
        
        private string shipping_FaxPhoneField;
        
        private string shipping_TimeToDepartureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Shipping_Name {
            get {
                return this.shipping_NameField;
            }
            set {
                this.shipping_NameField = value;
                this.RaisePropertyChanged("Shipping_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Shipping_Surname {
            get {
                return this.shipping_SurnameField;
            }
            set {
                this.shipping_SurnameField = value;
                this.RaisePropertyChanged("Shipping_Surname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Shipping_Email {
            get {
                return this.shipping_EmailField;
            }
            set {
                this.shipping_EmailField = value;
                this.RaisePropertyChanged("Shipping_Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Shipping_Address {
            get {
                return this.shipping_AddressField;
            }
            set {
                this.shipping_AddressField = value;
                this.RaisePropertyChanged("Shipping_Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Shipping_Address2 {
            get {
                return this.shipping_Address2Field;
            }
            set {
                this.shipping_Address2Field = value;
                this.RaisePropertyChanged("Shipping_Address2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Shipping_City {
            get {
                return this.shipping_CityField;
            }
            set {
                this.shipping_CityField = value;
                this.RaisePropertyChanged("Shipping_City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Shipping_StateCode {
            get {
                return this.shipping_StateCodeField;
            }
            set {
                this.shipping_StateCodeField = value;
                this.RaisePropertyChanged("Shipping_StateCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Shipping_Country {
            get {
                return this.shipping_CountryField;
            }
            set {
                this.shipping_CountryField = value;
                this.RaisePropertyChanged("Shipping_Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Shipping_PostalCode {
            get {
                return this.shipping_PostalCodeField;
            }
            set {
                this.shipping_PostalCodeField = value;
                this.RaisePropertyChanged("Shipping_PostalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Shipping_HomePhone {
            get {
                return this.shipping_HomePhoneField;
            }
            set {
                this.shipping_HomePhoneField = value;
                this.RaisePropertyChanged("Shipping_HomePhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Shipping_MobilePhone {
            get {
                return this.shipping_MobilePhoneField;
            }
            set {
                this.shipping_MobilePhoneField = value;
                this.RaisePropertyChanged("Shipping_MobilePhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Shipping_FaxPhone {
            get {
                return this.shipping_FaxPhoneField;
            }
            set {
                this.shipping_FaxPhoneField = value;
                this.RaisePropertyChanged("Shipping_FaxPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Shipping_TimeToDeparture {
            get {
                return this.shipping_TimeToDepartureField;
            }
            set {
                this.shipping_TimeToDepartureField = value;
                this.RaisePropertyChanged("Shipping_TimeToDeparture");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36323")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ecomm.sella.it/")]
    public partial class RedCustomerInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customer_TitleField;
        
        private string customer_NameField;
        
        private string customer_SurnameField;
        
        private string customer_EmailField;
        
        private string customer_AddressField;
        
        private string customer_Address2Field;
        
        private string customer_CityField;
        
        private string customer_StateCodeField;
        
        private string customer_CountryField;
        
        private string customer_PostalCodeField;
        
        private string customer_PhoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Customer_Title {
            get {
                return this.customer_TitleField;
            }
            set {
                this.customer_TitleField = value;
                this.RaisePropertyChanged("Customer_Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Customer_Name {
            get {
                return this.customer_NameField;
            }
            set {
                this.customer_NameField = value;
                this.RaisePropertyChanged("Customer_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Customer_Surname {
            get {
                return this.customer_SurnameField;
            }
            set {
                this.customer_SurnameField = value;
                this.RaisePropertyChanged("Customer_Surname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Customer_Email {
            get {
                return this.customer_EmailField;
            }
            set {
                this.customer_EmailField = value;
                this.RaisePropertyChanged("Customer_Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Customer_Address {
            get {
                return this.customer_AddressField;
            }
            set {
                this.customer_AddressField = value;
                this.RaisePropertyChanged("Customer_Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Customer_Address2 {
            get {
                return this.customer_Address2Field;
            }
            set {
                this.customer_Address2Field = value;
                this.RaisePropertyChanged("Customer_Address2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Customer_City {
            get {
                return this.customer_CityField;
            }
            set {
                this.customer_CityField = value;
                this.RaisePropertyChanged("Customer_City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Customer_StateCode {
            get {
                return this.customer_StateCodeField;
            }
            set {
                this.customer_StateCodeField = value;
                this.RaisePropertyChanged("Customer_StateCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Customer_Country {
            get {
                return this.customer_CountryField;
            }
            set {
                this.customer_CountryField = value;
                this.RaisePropertyChanged("Customer_Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Customer_PostalCode {
            get {
                return this.customer_PostalCodeField;
            }
            set {
                this.customer_PostalCodeField = value;
                this.RaisePropertyChanged("Customer_PostalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Customer_Phone {
            get {
                return this.customer_PhoneField;
            }
            set {
                this.customer_PhoneField = value;
                this.RaisePropertyChanged("Customer_Phone");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36323")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ecomm.sella.it/")]
    public partial class PaymentTypeDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string myBankBankCodeField;
        
        private string idealBankCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MyBankBankCode {
            get {
                return this.myBankBankCodeField;
            }
            set {
                this.myBankBankCodeField = value;
                this.RaisePropertyChanged("MyBankBankCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IdealBankCode {
            get {
                return this.idealBankCodeField;
            }
            set {
                this.idealBankCodeField = value;
                this.RaisePropertyChanged("IdealBankCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Encrypt", WrapperNamespace="https://ecomm.sella.it/", IsWrapped=true)]
    public partial class EncryptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ecomm.sella.it/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string shopLogin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ecomm.sella.it/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string uicCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ecomm.sella.it/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ecomm.sella.it/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string shopTransactionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ecomm.sella.it/", Order=4)]
        public string cardNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ecomm.sella.it/", Order=5)]
        public string expiryMonth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ecomm.sella.it/", Order=6)]
        public string expiryYear;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ecomm.sella.it/", Order=7)]
        public string buyerName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ecomm.sella.it/", Order=8)]
        public string buyerEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ecomm.sella.it/", Order=9)]
        public string languageId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ecomm.sella.it/", Order=10)]
        public string cvv;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ecomm.sella.it/", Order=11)]
        public string customInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ecomm.sella.it/", Order=12)]
        public string requestToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ecomm.sella.it/", Order=13)]
        public string ppSellerProtection;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ecomm.sella.it/", Order=14)]
        public GhigoWeb.BancaSellaWS.ShippingDetails shippingDetails;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ecomm.sella.it/", Order=15)]
        [System.Xml.Serialization.XmlArrayItemAttribute("paymentType", IsNullable=false)]
        public string[] paymentTypes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ecomm.sella.it/", Order=16)]
        public GhigoWeb.BancaSellaWS.PaymentTypeDetail paymentTypeDetail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ecomm.sella.it/", Order=17)]
        public string redFraudPrevention;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ecomm.sella.it/", Order=18)]
        public GhigoWeb.BancaSellaWS.RedCustomerInfo Red_CustomerInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ecomm.sella.it/", Order=19)]
        public GhigoWeb.BancaSellaWS.RedShippingInfo Red_ShippingInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ecomm.sella.it/", Order=20)]
        public GhigoWeb.BancaSellaWS.RedBillingInfo Red_BillingInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ecomm.sella.it/", Order=21)]
        public GhigoWeb.BancaSellaWS.RedCustomerData Red_CustomerData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ecomm.sella.it/", Order=22)]
        [System.Xml.Serialization.XmlArrayItemAttribute("UserCustomData", IsNullable=false)]
        public string[] Red_CustomInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ecomm.sella.it/", Order=23)]
        public GhigoWeb.BancaSellaWS.RedItems Red_Items;
        
        public EncryptRequest() {
        }
        
        public EncryptRequest(
                    string shopLogin, 
                    string uicCode, 
                    string amount, 
                    string shopTransactionId, 
                    string cardNumber, 
                    string expiryMonth, 
                    string expiryYear, 
                    string buyerName, 
                    string buyerEmail, 
                    string languageId, 
                    string cvv, 
                    string customInfo, 
                    string requestToken, 
                    string ppSellerProtection, 
                    GhigoWeb.BancaSellaWS.ShippingDetails shippingDetails, 
                    string[] paymentTypes, 
                    GhigoWeb.BancaSellaWS.PaymentTypeDetail paymentTypeDetail, 
                    string redFraudPrevention, 
                    GhigoWeb.BancaSellaWS.RedCustomerInfo Red_CustomerInfo, 
                    GhigoWeb.BancaSellaWS.RedShippingInfo Red_ShippingInfo, 
                    GhigoWeb.BancaSellaWS.RedBillingInfo Red_BillingInfo, 
                    GhigoWeb.BancaSellaWS.RedCustomerData Red_CustomerData, 
                    string[] Red_CustomInfo, 
                    GhigoWeb.BancaSellaWS.RedItems Red_Items) {
            this.shopLogin = shopLogin;
            this.uicCode = uicCode;
            this.amount = amount;
            this.shopTransactionId = shopTransactionId;
            this.cardNumber = cardNumber;
            this.expiryMonth = expiryMonth;
            this.expiryYear = expiryYear;
            this.buyerName = buyerName;
            this.buyerEmail = buyerEmail;
            this.languageId = languageId;
            this.cvv = cvv;
            this.customInfo = customInfo;
            this.requestToken = requestToken;
            this.ppSellerProtection = ppSellerProtection;
            this.shippingDetails = shippingDetails;
            this.paymentTypes = paymentTypes;
            this.paymentTypeDetail = paymentTypeDetail;
            this.redFraudPrevention = redFraudPrevention;
            this.Red_CustomerInfo = Red_CustomerInfo;
            this.Red_ShippingInfo = Red_ShippingInfo;
            this.Red_BillingInfo = Red_BillingInfo;
            this.Red_CustomerData = Red_CustomerData;
            this.Red_CustomInfo = Red_CustomInfo;
            this.Red_Items = Red_Items;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EncryptResponse", WrapperNamespace="https://ecomm.sella.it/", IsWrapped=true)]
    public partial class EncryptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ecomm.sella.it/", Order=0)]
        public System.Xml.XmlNode EncryptResult;
        
        public EncryptResponse() {
        }
        
        public EncryptResponse(System.Xml.XmlNode EncryptResult) {
            this.EncryptResult = EncryptResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSCryptDecryptSoapChannel : GhigoWeb.BancaSellaWS.WSCryptDecryptSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSCryptDecryptSoapClient : System.ServiceModel.ClientBase<GhigoWeb.BancaSellaWS.WSCryptDecryptSoap>, GhigoWeb.BancaSellaWS.WSCryptDecryptSoap {
        
        public WSCryptDecryptSoapClient() {
        }
        
        public WSCryptDecryptSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSCryptDecryptSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCryptDecryptSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCryptDecryptSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GhigoWeb.BancaSellaWS.EncryptResponse GhigoWeb.BancaSellaWS.WSCryptDecryptSoap.Encrypt(GhigoWeb.BancaSellaWS.EncryptRequest request) {
            return base.Channel.Encrypt(request);
        }
        
        public System.Xml.XmlNode Encrypt(
                    string shopLogin, 
                    string uicCode, 
                    string amount, 
                    string shopTransactionId, 
                    string cardNumber, 
                    string expiryMonth, 
                    string expiryYear, 
                    string buyerName, 
                    string buyerEmail, 
                    string languageId, 
                    string cvv, 
                    string customInfo, 
                    string requestToken, 
                    string ppSellerProtection, 
                    GhigoWeb.BancaSellaWS.ShippingDetails shippingDetails, 
                    string[] paymentTypes, 
                    GhigoWeb.BancaSellaWS.PaymentTypeDetail paymentTypeDetail, 
                    string redFraudPrevention, 
                    GhigoWeb.BancaSellaWS.RedCustomerInfo Red_CustomerInfo, 
                    GhigoWeb.BancaSellaWS.RedShippingInfo Red_ShippingInfo, 
                    GhigoWeb.BancaSellaWS.RedBillingInfo Red_BillingInfo, 
                    GhigoWeb.BancaSellaWS.RedCustomerData Red_CustomerData, 
                    string[] Red_CustomInfo, 
                    GhigoWeb.BancaSellaWS.RedItems Red_Items) {
            GhigoWeb.BancaSellaWS.EncryptRequest inValue = new GhigoWeb.BancaSellaWS.EncryptRequest();
            inValue.shopLogin = shopLogin;
            inValue.uicCode = uicCode;
            inValue.amount = amount;
            inValue.shopTransactionId = shopTransactionId;
            inValue.cardNumber = cardNumber;
            inValue.expiryMonth = expiryMonth;
            inValue.expiryYear = expiryYear;
            inValue.buyerName = buyerName;
            inValue.buyerEmail = buyerEmail;
            inValue.languageId = languageId;
            inValue.cvv = cvv;
            inValue.customInfo = customInfo;
            inValue.requestToken = requestToken;
            inValue.ppSellerProtection = ppSellerProtection;
            inValue.shippingDetails = shippingDetails;
            inValue.paymentTypes = paymentTypes;
            inValue.paymentTypeDetail = paymentTypeDetail;
            inValue.redFraudPrevention = redFraudPrevention;
            inValue.Red_CustomerInfo = Red_CustomerInfo;
            inValue.Red_ShippingInfo = Red_ShippingInfo;
            inValue.Red_BillingInfo = Red_BillingInfo;
            inValue.Red_CustomerData = Red_CustomerData;
            inValue.Red_CustomInfo = Red_CustomInfo;
            inValue.Red_Items = Red_Items;
            GhigoWeb.BancaSellaWS.EncryptResponse retVal = ((GhigoWeb.BancaSellaWS.WSCryptDecryptSoap)(this)).Encrypt(inValue);
            return retVal.EncryptResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GhigoWeb.BancaSellaWS.EncryptResponse> GhigoWeb.BancaSellaWS.WSCryptDecryptSoap.EncryptAsync(GhigoWeb.BancaSellaWS.EncryptRequest request) {
            return base.Channel.EncryptAsync(request);
        }
        
        public System.Threading.Tasks.Task<GhigoWeb.BancaSellaWS.EncryptResponse> EncryptAsync(
                    string shopLogin, 
                    string uicCode, 
                    string amount, 
                    string shopTransactionId, 
                    string cardNumber, 
                    string expiryMonth, 
                    string expiryYear, 
                    string buyerName, 
                    string buyerEmail, 
                    string languageId, 
                    string cvv, 
                    string customInfo, 
                    string requestToken, 
                    string ppSellerProtection, 
                    GhigoWeb.BancaSellaWS.ShippingDetails shippingDetails, 
                    string[] paymentTypes, 
                    GhigoWeb.BancaSellaWS.PaymentTypeDetail paymentTypeDetail, 
                    string redFraudPrevention, 
                    GhigoWeb.BancaSellaWS.RedCustomerInfo Red_CustomerInfo, 
                    GhigoWeb.BancaSellaWS.RedShippingInfo Red_ShippingInfo, 
                    GhigoWeb.BancaSellaWS.RedBillingInfo Red_BillingInfo, 
                    GhigoWeb.BancaSellaWS.RedCustomerData Red_CustomerData, 
                    string[] Red_CustomInfo, 
                    GhigoWeb.BancaSellaWS.RedItems Red_Items) {
            GhigoWeb.BancaSellaWS.EncryptRequest inValue = new GhigoWeb.BancaSellaWS.EncryptRequest();
            inValue.shopLogin = shopLogin;
            inValue.uicCode = uicCode;
            inValue.amount = amount;
            inValue.shopTransactionId = shopTransactionId;
            inValue.cardNumber = cardNumber;
            inValue.expiryMonth = expiryMonth;
            inValue.expiryYear = expiryYear;
            inValue.buyerName = buyerName;
            inValue.buyerEmail = buyerEmail;
            inValue.languageId = languageId;
            inValue.cvv = cvv;
            inValue.customInfo = customInfo;
            inValue.requestToken = requestToken;
            inValue.ppSellerProtection = ppSellerProtection;
            inValue.shippingDetails = shippingDetails;
            inValue.paymentTypes = paymentTypes;
            inValue.paymentTypeDetail = paymentTypeDetail;
            inValue.redFraudPrevention = redFraudPrevention;
            inValue.Red_CustomerInfo = Red_CustomerInfo;
            inValue.Red_ShippingInfo = Red_ShippingInfo;
            inValue.Red_BillingInfo = Red_BillingInfo;
            inValue.Red_CustomerData = Red_CustomerData;
            inValue.Red_CustomInfo = Red_CustomInfo;
            inValue.Red_Items = Red_Items;
            return ((GhigoWeb.BancaSellaWS.WSCryptDecryptSoap)(this)).EncryptAsync(inValue);
        }
        
        public System.Xml.XmlNode Decrypt(string shopLogin, string CryptedString) {
            return base.Channel.Decrypt(shopLogin, CryptedString);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> DecryptAsync(string shopLogin, string CryptedString) {
            return base.Channel.DecryptAsync(shopLogin, CryptedString);
        }
    }
}
